---
- name: Install apt-transport-https
  remote_user: deployer
  apt:
    state: latest
    update_cache: true

- name: Add Apt signing key
  remote_user: deployer
  apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present

- name: Add repository into sources list
  remote_user: deployer
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install google-chrome-stable
  remote_user: deployer
  apt:
    name: "google-chrome-stable"
    state: latest
    update_cache: true
