---
- name: Install required packages
  remote_user: deployer
  apt:
    name:
      - python3-pip
      - chromium-browser
      - chromium-chromedriver
    state: present

- name: Install Selenium module
  remote_user: deployer
  pip:
    name: selenium
    state: present

- name: Download Chrome Driver
  remote_user: deployer
  get_url:
    url: https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_linux64.zip
    dest: /tmp/chromedriver.zip
    mode: '0755'

- name: Extract Chrome Driver
  remote_user: deployer
  unarchive:
    src: /tmp/chromedriver.zip
    dest: /usr/local/bin/
    copy: no
    owner: root
    mode: '0755'
