---
- name: Deploy Jenkins
  hosts: terra_ansible_host
  become: true
  gather_facts: false

  roles:
    - create_deployer_user
    - install_jenkins_docker
    - install_chromedriver_selenium
    - install_chrome_debian
